<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class SaveReservation extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'reservation_started_at' => 'bail|required|date|before:reservation_ended_at|after:yesterday',
            'reservation_ended_at' => 'bail|required|date|after:reservation_started_at',
            'reservation_guest_started_at.*' => 'bail|required|date|before:reservation_guest_ended_at.*|after_or_equal:reservation_started_at',
            'reservation_guest_ended_at.*' => 'bail|required|date|after:reservation_guest_started_at.*|before_or_equal:reservation_ended_at',
            'number_nights.*' => 'bail|required|min:1',
            'reservation_guest_guests.*' => 'bail|required|min:1',
            'reservation_guest_price.*' => 'bail|required|min:1',
            'reservation_guest_num.*' => 'bail|required|min:1'
        ];
    }

    protected function getValidatorInstance()
    {
        $requestData = $this->all();
        foreach ($requestData as $key => $data) {
            if (is_array($data)) {
                foreach ($data as $k => $d) {
                    $requestData[$key . '_' . $k] = $d;
                }
            }
        }
        /*
        foreach($data['reservation_guest_ended_at'] as $k => $d) {
            $tmp = explode('.', $d);
            $data['reservation_guest_ended_at'][$k] = $tmp[2] . '-' . $tmp[1] . '-' . $tmp[0];
        }
        foreach($data['reservation_guest_started_at'] as $k => $d) {
            $tmp = explode('.', $d);
            $data['reservation_guest_started_at'][$k] = $tmp[2] . '-' . $tmp[1] . '-' . $tmp[0];
        }
        */
        //$this->getInputSource()->replace($requestData);
        return parent::getValidatorInstance(); // TODO: Change the autogenerated stub
    }
}
